theme: minima
title: Niklas Personal Space
author: Niklas Josef Palm
email: niklas.palm@rwth-aachen.de
description: > # this means to ignore newlines until "baseurl:"
  I blog about Apple stuff and sometimes about mental health.
# social links
twitter_username: niklasjpalm # DO NOT include the @ character, or else the build will fail!
github_username:  Nikipe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
